{{- /*
This template is for creating secrets.
By default, it can create a secret for the database password.
In production, it is recommended to manage secrets outside of the Helm chart,
for example with Sealed Secrets or an external secret store.
*/}}

{{- if .Values.database.passwordSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.passwordSecret.name }}
  labels:
    {{- include "quantacirc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.passwordSecret.key }}: {{ .Values.database.passwordSecret.value | b64enc | quote }}
{{- end }}
