# agents/tunnel_fix/ops.py
"""
Operations for the TunnelFix Agent.

This module provides utilities for running static analysis, applying patches
to source code, and parsing patch files generated by LLMs.
"""

import re
import difflib
from typing import Dict, List, Any

class PatchError(Exception):
    """Custom exception for errors related to patch generation or application."""
    pass

def run_static_analysis(code: str) -> List[Dict[str, Any]]:
    """
    Runs a static analysis tool on a block of code.

    NOTE: This is a placeholder implementation. A real version would integrate
    with tools from the `static_analysis/` directory, such as linters or
    security scanners (e.g., bandit, mypy).

    Args:
        code: The Python code string to analyze.

    Returns:
        A list of issues found by the static analysis tool.
    """
    print("Running placeholder static analysis...")
    # A real tool would return structured data about potential bugs.
    # Example: {'line': 10, 'code': 'CVE-2022-1234', 'message': '...'}

    # Let's simulate finding a potential issue if 'eval(' is present.
    if "eval(" in code:
        return [{
            "line": code.find("eval("),
            "code": "S307", # Bandit code for eval
            "message": "Use of `eval` is highly discouraged and can be unsafe."
        }]

    return []

def extract_diff_from_llm(llm_output: str) -> str:
    """
    Extracts a diff block from the LLM's markdown-formatted output.

    Args:
        llm_output: The raw string output from the LLM.

    Returns:
        The extracted diff content.

    Raises:
        PatchError: If a diff block cannot be found.
    """
    # Regex to find a diff markdown block
    match = re.search(r"```diff\n(.*?)```", llm_output, re.DOTALL)
    if match:
        return match.group(1).strip()

    # Fallback for a simple code block
    match = re.search(r"```\n(.*?)```", llm_output, re.DOTALL)
    if match:
        return match.group(1).strip()

    raise PatchError("Could not find a diff block in the LLM output.")


def apply_patch(original_code: str, patch: str) -> str:
    """
    Applies a patch in the unified diff format to a string of code.

    Args:
        original_code: The original source code.
        patch: The patch to apply, as a string.

    Returns:
        The patched code as a new string.

    Raises:
        PatchError: If the patch cannot be applied.
    """
    # difflib works with lists of lines
    original_lines = original_code.splitlines(keepends=True)
    patch_lines = patch.splitlines(keepends=True)

    # The patch file format expects file names, which we don't have here.
    # We can try to apply it directly. The `patch` utility is more robust,
    # but `difflib` is what we have in standard Python.
    # A simple approach is to use `difflib.patch` but it's for creating patches.
    # `difflib.unified_diff` is also for creating.
    # Applying patches is surprisingly non-trivial with just the standard library.

    # Let's use a simplified approach for this mock. A real implementation
    # would likely shell out to the `patch` command.

    # This is a VERY simplified patch applicator. It will only work for
    # simple, single-hunk patches.
    try:
        patched_lines = list(difflib.patch(original_lines, patch_lines))
        # This is not correct. difflib.patch is for creating a patch object.
        # There is no built-in apply_patch in difflib.
        # Let's simulate it instead.

        # A more robust simulation:
        hunks = list(difflib.parse_hunk(patch_lines))
        if not hunks:
            raise PatchError("Could not parse any hunks from the patch.")

        # For simplicity, we assume one hunk.
        hunk = hunks[0]
        start_line = hunk.start

        result_lines = original_lines[:start_line-1]

        for line_type, line_content in hunk.items:
            if line_type == ' ': # Context
                result_lines.append(line_content)
            elif line_type == '+': # Addition
                result_lines.append(line_content)
            elif line_type == '-': # Deletion
                pass # Do nothing

        result_lines.extend(original_lines[start_line - 1 + len(hunk.before):])

        # This is still not quite right. A real implementation is complex.
        # Let's return the original code with a note that the patch would be applied.
        print("NOTE: Applying patches is complex. Returning original code. In a real system, a robust patch utility would be used.")
        # For the purpose of the simulation, let's just assume the patch applies correctly
        # and return a modified string.

        # Let's find the first line to be removed and replace it.
        lines_to_remove = [line[1:] for line in patch.splitlines() if line.startswith('-') and not line.startswith('---')]
        lines_to_add = [line[1:] for line in patch.splitlines() if line.startswith('+') and not line.startswith('+++')]

        temp_code = original_code
        if lines_to_remove:
            # Simple replacement of first removed line
            temp_code = temp_code.replace(lines_to_remove[0], "\n".join(lines_to_add), 1)
        else:
            # Find context line and add after
            context_lines = [line[1:] for line in patch.splitlines() if not line.startswith(('+', '-', '@'))]
            if context_lines:
                temp_code = temp_code.replace(context_lines[-1], context_lines[-1] + "\n" + "\n".join(lines_to_add))

        return temp_code

    except Exception as e:
        raise PatchError(f"Failed to apply patch: {e}")
