# agents/planck_forge/agent.py
"""
PlanckForge Agent: Translates natural language requirements into formal task sets.

This agent is the first step in the quantum software engineering process,
decomposing high-level goals into a structured, verifiable, and machine-readable
format.
"""

from typing import Dict, Any, Optional, List

from agents.base.agent import QuantumAgent
from core.state_space import StateSpace
from core.energy_calculator import EnergyCalculator
from core.types import AgentTask as Proposal, QCState as State, AgentResult as Action, Status
from monitoring.metrics import QuantumMetrics as MetricsLogger
from agents.base.policies import PolicyEngine
from agents.base.memory import AgentMemory
from llm.client import LLMClient

from . import prompts
from . import ops

class PlanckForgeAgent(QuantumAgent):
    """
    The PlanckForge Agent specializes in requirement quantization.

    It uses an LLM to analyze natural language requirements and structures them
    into a formal task dependency graph (DAG). Its rigor is Functor-Verified,
    ensuring that the output is logically sound and adheres to predefined
    closure rules.
    """
    def __init__(
        self,
        state_space: StateSpace,
        energy_calculator: EnergyCalculator,
        metrics_logger: MetricsLogger,
        policy_engine: PolicyEngine,
        agent_memory: AgentMemory,
        llm_client: LLMClient,
        agent_id: Optional[str] = None,
    ):
        super().__init__(
            name="planck_forge",
            state_space=state_space,
            energy_calculator=energy_calculator,
            metrics_logger=metrics_logger,
            policy_engine=policy_engine,
            agent_memory=agent_memory,
            agent_id=agent_id,
        )
        self.llm_client = llm_client

    async def analyze_state(self, state: State) -> Proposal:
        """
        Analyzes a state containing a natural language requirement.

        Args:
            state: The current state, expected to have a 'requirement_text' field in metadata.

        Returns:
            A proposal containing the decomposed tasks.
        """
        requirement_text = state.metadata.get("requirement_text")
        if not requirement_text:
            return Proposal(agent_name=self.name, task_type="analysis", payload={}, status=Status.FAILED, reason="No requirement text found in state.")

        # 1. Get the appropriate prompt
        prompt_spec = prompts.get_prompt("decompose_requirement", "latest")
        formatted_prompt = prompt_spec.format(requirement_text=requirement_text)

        # 2. Call the LLM
        llm_response = await self.llm_client.complete({"prompt": formatted_prompt})

        if not llm_response.get("content"):
            return Proposal(agent_name=self.name, task_type="analysis", payload={}, status=Status.FAILED, reason="LLM failed to provide content.")

        # 3. Parse the LLM output
        try:
            tasks = ops.parse_llm_output(llm_response["content"])
            return Proposal(
                agent_name=self.name,
                task_type="analysis",
                payload={"tasks": tasks, "requirement_text": requirement_text},
                status=Status.SUCCESS
            )
        except ops.TaskValidationError as e:
            return Proposal(agent_name=self.name, task_type="analysis", payload={}, status=Status.FAILED, reason=f"Failed to parse or validate LLM output: {e}")

    def validate_proposal(self, proposal: Proposal) -> bool:
        """
        Validates the task set in the proposal using closure rules.

        Args:
            proposal: The proposal generated by analyze_state.

        Returns:
            True if the proposal is valid, False otherwise.
        """
        if proposal.status != Status.SUCCESS or "tasks" not in proposal.payload:
            return False

        try:
            ops.validate_task_set(proposal.payload["tasks"])
            self.metrics_logger.increment_counter(f"agent_{self.name}_proposal_validation_success")
            return True
        except ops.TaskValidationError as e:
            self.metrics_logger.increment_counter(f"agent_{self.name}_proposal_validation_failure")
            print(f"Proposal validation failed for agent {self.name}: {e}")
            return False

    def execute(self, proposal: Proposal) -> Action:
        """
        Executes the proposal by finalizing the task DAG and calculating energy.

        Args:
            proposal: A validated proposal.

        Returns:
            An action containing the task DAG and energy impact.
        """
        tasks = proposal.payload["tasks"]

        # 1. Generate the final task DAG
        task_dag = ops.generate_task_dag(tasks)

        # 2. Calculate the static energy impact
        num_tasks = len(tasks)
        num_dependencies = sum(len(task.get('dependencies', [])) for task in tasks)

        static_metrics = {
            'cyclomatic_complexity': float(num_tasks),
            'coupling': float(num_dependencies)
        }

        static_energy = self.energy_calculator.compute_static_energy(static_metrics)

        # 3. Create the action
        action_data = {
            "task_dag": task_dag,
            "original_requirement": proposal.payload["requirement_text"],
            "energy_impact": {
                "static": static_energy
            }
        }

        return Action(
            task_id=proposal.id,
            agent_name=self.name,
            action_taken=True,
            status=Status.SUCCESS,
            result=action_data
        )
