# agents/phonon_flow/ops.py
"""
Operations for the PhononFlow Agent.

This module provides utilities for analyzing data flow patterns in code
and parsing optimization plans generated by LLMs.
"""

import json
from typing import Dict, Any

class DataFlowError(Exception):
    """Custom exception for errors during data flow analysis."""
    pass

def analyze_data_flow(file_map: Dict[str, str]) -> str:
    """
    Analyzes the codebase to identify and describe data flow patterns.

    NOTE: This is a placeholder implementation. A real version would use
    static analysis (AST parsing) to find network calls (e.g., `requests.get`),
    database queries (e.g., `cursor.execute`), and other forms of inter-component
    communication.

    Args:
        file_map: A dictionary mapping file paths to their code content.

    Returns:
        A natural language description of a data flow pattern found in the code.
    """
    print("Running placeholder data flow analysis...")

    # Simulate finding a synchronous API call pattern between two components.
    for file_path, code in file_map.items():
        if "requests.get" in code or "requests.post" in code:
            # Found a file making an HTTP request.
            # This is a good candidate for optimization analysis.
            description = (
                f"The component defined in `{file_path}` appears to make a synchronous "
                "HTTP request to an external service. This can lead to high latency if the "
                "external service is slow. The system must wait for the request to complete "
                "before continuing execution. This pattern is often a key performance bottleneck."
            )
            return description

    return "No clear inter-component data flow patterns were identified."

def parse_optimization_plan(llm_output: str) -> Dict[str, Any]:
    """
    Parses the JSON output from the LLM into a data flow optimization plan.

    Args:
        llm_output: The raw string output from the LLM.

    Returns:
        A dictionary representing the optimization plan.

    Raises:
        DataFlowError: If the output is not valid JSON or if the structure is incorrect.
    """
    try:
        plan = json.loads(llm_output)
        required_keys = ["analysis", "proposed_pattern", "implementation_plan", "expected_outcome"]
        if not all(key in plan for key in required_keys):
            raise DataFlowError("LLM output is missing required keys for the optimization plan.")
        return plan
    except json.JSONDecodeError:
        raise DataFlowError("Failed to decode LLM output as JSON.")
