# agents/phonon_flow/ops.py
"""
Operations for the PhononFlow Agent.

This module provides utilities for analyzing data flow patterns in code
and parsing optimization plans generated by LLMs.
"""

import json
import ast
from typing import Dict, Any

class DataFlowError(Exception):
    """Custom exception for errors during data flow analysis."""
    pass

class CallVisitor(ast.NodeVisitor):
    def __init__(self):
        self.calls = []

    def visit_Call(self, node):
        if isinstance(node.func, ast.Attribute):
            self.calls.append(node.func.attr)
        elif isinstance(node.func, ast.Name):
            self.calls.append(node.func.id)
        self.generic_visit(node)

def analyze_data_flow(file_map: Dict[str, str]) -> str:
    """
    Analyzes the codebase to identify and describe data flow patterns.
    """
    for file_path, code in file_map.items():
        try:
            tree = ast.parse(code)
            visitor = CallVisitor()
            visitor.visit(tree)

            # Look for common network request patterns
            if any(call in ['get', 'post', 'put', 'delete'] for call in visitor.calls):
                description = (
                    f"The component defined in `{file_path}` appears to make a synchronous "
                    "HTTP request. This can lead to high latency if the "
                    "external service is slow."
                )
                return description
        except SyntaxError:
            continue

    return "No clear inter-component data flow patterns were identified."

def parse_optimization_plan(llm_output: str) -> Dict[str, Any]:
    """
    Parses the JSON output from the LLM into a data flow optimization plan.
    """
    try:
        plan = json.loads(llm_output)
        required_keys = ["analysis", "proposed_pattern", "implementation_plan", "expected_outcome"]
        if not all(key in plan for key in required_keys):
            raise DataFlowError("LLM output is missing required keys for the optimization plan.")
        return plan
    except json.JSONDecodeError:
        raise DataFlowError("Failed to decode LLM output as JSON.")
