# agents/pauli_guard/agent.py
"""
PauliGuard Agent: Enforces orthogonality by detecting and eliminating
code duplication.

This agent analyzes code generated by SchrodingerDev to find duplicated or
highly similar code blocks and proposes refactoring plans to abstract them
into shared components.
"""
import asyncio
import json
from typing import Dict, Any, Optional, List

from agents.base.agent import QuantumAgent
from core.state_space import StateSpace
from core.energy_calculator import EnergyCalculator
from core.types import AgentTask as Proposal, QCState as State, AgentResult as Action, Status
from monitoring.metrics import QuantumMetrics as MetricsLogger
from agents.base.policies import PolicyEngine
from agents.base.memory import AgentMemory
from llm.client import LLMClient

from . import prompts
from . import ops

class PauliGuardAgent(QuantumAgent):
    """
    The PauliGuard Agent maintains code orthogonality.

    It acts as a quality gate, identifying redundant code and proposing
    refactorings to improve maintainability and reduce coupling. Its rigor is
    Functor-Verified, as the proposed refactorings must be proven to be
    semantically equivalent to the original code.
    """
    def __init__(
        self,
        state_space: StateSpace,
        energy_calculator: EnergyCalculator,
        metrics_logger: MetricsLogger,
        policy_engine: PolicyEngine,
        agent_memory: AgentMemory,
        llm_client: LLMClient,
        config: Optional[Dict[str, Any]] = None,
        agent_id: Optional[str] = None,
    ):
        super().__init__(
            name="pauli_guard",
            state_space=state_space,
            energy_calculator=energy_calculator,
            metrics_logger=metrics_logger,
            policy_engine=policy_engine,
            agent_memory=agent_memory,
            agent_id=agent_id,
        )
        self.llm_client = llm_client
        self.config = config or {}

    async def analyze_state(self, state: State) -> Proposal:
        """
        Analyzes the code from the previous state for duplication.

        Args:
            state: The current state, expected to contain the output from SchrodingerDev.

        Returns:
            A proposal containing refactoring plans for any detected duplicates.
        """
        schrodinger_dev_output = state.metadata.get("schrodinger_dev_output", {})
        files_to_check = schrodinger_dev_output.get("files_to_create", {})

        if not files_to_check:
            # No files to check, so no work to do.
            return Proposal(agent_name=self.name, task_type="refactor", payload={"refactoring_plans": []}, status=Status.SUCCESS)

        # 1. Detect duplicates
        duplicates = ops.detect_duplicates(
            files_to_check,
            min_lines=self.config.get("min_lines_for_duplication", 5),
            similarity_threshold=self.config.get("similarity_threshold", 0.95)
        )

        if not duplicates:
            return Proposal(agent_name=self.name, task_type="refactor", payload={"refactoring_plans": []}, status=Status.SUCCESS, reason="No duplicates found.")

        # 2. Generate refactoring plans for each duplicate
        plan_coros = []
        for dup in duplicates:
            plan_coros.append(self._generate_refactoring_plan(dup))

        refactoring_plans = await asyncio.gather(*plan_coros, return_exceptions=True)

        valid_plans = [p for p in refactoring_plans if not isinstance(p, Exception)]

        return Proposal(
            agent_name=self.name,
            task_type="refactor",
            payload={"refactoring_plans": valid_plans, "duplicates_found": duplicates},
            status=Status.SUCCESS
        )

    async def _generate_refactoring_plan(self, duplicate_info: Dict[str, Any]) -> Dict[str, Any]:
        """Helper to generate a refactoring plan for a single duplicate pair."""
        prompt_spec = prompts.get_prompt("generate_refactoring_plan")
        formatted_prompt = prompt_spec.format(
            file_path_1=duplicate_info["block_1"]["file_path"],
            code_block_1=duplicate_info["block_1"]["content"],
            file_path_2=duplicate_info["block_2"]["file_path"],
            code_block_2=duplicate_info["block_2"]["content"]
        )

        llm_response = await self.llm_client.complete({"prompt": formatted_prompt})
        plan = ops.parse_refactoring_plan(llm_response["content"])
        return plan

    def validate_proposal(self, proposal: Proposal) -> bool:
        """
        Validates the refactoring plans in the proposal.

        A real implementation would involve semantic checks, but for now, we
        just check the structure of the plans.
        """
        if proposal.status != Status.SUCCESS:
            return False

        for plan in proposal.payload.get("refactoring_plans", []):
            try:
                # Re-run the parser to validate structure
                ops.parse_refactoring_plan(json.dumps(plan))
            except ops.RefactoringPlanError as e:
                print(f"Refactoring plan validation failed: {e}")
                return False

        return True

    def execute(self, proposal: Proposal) -> Action:
        """
        Executes the proposal by calculating the energy impact of the refactoring.
        """
        refactoring_plans = proposal.payload.get("refactoring_plans", [])
        duplicates = proposal.payload.get("duplicates_found", [])

        # 1. Calculate the reduction in interaction energy
        # A simple model: energy reduction is proportional to the number and size of duplicates found.
        # This represents a reduction in coupling.
        coupling_reduction = 0
        for dup in duplicates:
            # Add the lengths of the two duplicated blocks
            coupling_reduction += len(dup["block_1"]["content"]) + len(dup["block_2"]["content"])

        # This metric can be used by the energy calculator
        interaction_metrics = {
            "coupling_reduction": float(coupling_reduction)
        }

        # We assume the calculator can handle a negative contribution
        # or has a specific method for calculating energy changes.
        # For now, let's calculate a simple negative energy impact.
        # Let's say each character of duplicated code removed reduces energy.
        energy_reduction = self.energy_calculator.config.get("w_coupling_reduction", 0.1) * coupling_reduction

        # 2. Create the action
        action_data = {
            "refactoring_plans": refactoring_plans,
            "energy_impact": {
                # This is an energy *reduction*
                "interaction": -energy_reduction
            }
        }

        return Action(
            task_id=proposal.id,
            agent_name=self.name,
            action_taken=True,
            status=Status.SUCCESS,
            result=action_data,
        )
