# agents/pauli_guard/agent.py
"""
PauliGuard Agent: Enforces orthogonality by detecting and eliminating
code duplication.

This agent analyzes code generated by SchrodingerDev to find duplicated or
highly similar code blocks and proposes refactoring plans to abstract them
into shared components.
"""
import json
import ast
import asyncio
import numpy as np
import networkx as nx
from typing import Dict, Any, Optional, List
from sklearn.feature_extraction.text import TfidfVectorizer

from agents.base.agent import QuantumAgent
from agents.base.contracts import Contract, Condition
from core.state_space import StateSpace
from core.energy_calculator import EnergyCalculator
from core.types import AgentTask as Proposal, QCState as State, AgentResult as Action, Status
from monitoring.metrics import QuantumMetrics as MetricsLogger
from agents.base.policies import PolicyEngine
from agents.base.memory import AgentMemory
from llm.client import LLMClient

from . import prompts
from . import ops
from . import similarity_ops

class PauliGuardAgent(QuantumAgent):
    """
    The PauliGuard Agent maintains code orthogonality.

    It acts as a quality gate, identifying redundant code and proposing
    refactorings to improve maintainability and reduce coupling. Its rigor is
    Functor-Verified, as the proposed refactorings must be proven to be
    semantically equivalent to the original code.
    """
    def __init__(
        self,
        state_space: StateSpace,
        energy_calculator: EnergyCalculator,
        metrics_logger: MetricsLogger,
        policy_engine: PolicyEngine,
        agent_memory: AgentMemory,
        llm_client: LLMClient,
        config: Optional[Dict[str, Any]] = None,
        agent_id: Optional[str] = None,
    ):
        class ModuleCountCondition(Condition):
            def check(self, state: State, **kwargs) -> bool:
                # This condition logic might need adjustment based on how modules are tracked.
                # For now, we check if there are files to process.
                schrodinger_dev_output = state.metadata.get("schrodinger_dev_output", {})
                files_to_check = schrodinger_dev_output.get("files_to_create", {})
                return len(files_to_check) >= 2

        contracts = [
            Contract(
                name="file_count",
                preconditions=[ModuleCountCondition()],
                postconditions=[],
            )
        ]
        super().__init__(
            name="pauli_guard",
            state_space=state_space,
            energy_calculator=energy_calculator,
            metrics_logger=metrics_logger,
            policy_engine=policy_engine,
            agent_memory=agent_memory,
            contracts=contracts,
            agent_id=agent_id,
        )
        self.llm_client = llm_client
        self.config = config or {}

    def _extract_code_blocks(self, file_map: Dict[str, str]) -> List[Dict[str, Any]]:
        """A simplified block extractor, borrowing from ops.py."""
        all_blocks = []
        min_lines = self.config.get("min_lines_for_duplication", 5)
        for file_path, content in file_map.items():
            try:
                tree = ast.parse(content)
                for node in ast.walk(tree):
                    if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
                        block_content = ast.unparse(node)
                        if len(block_content.splitlines()) < min_lines:
                            continue
                        all_blocks.append({
                            "file_path": file_path,
                            "content": block_content,
                            "normalized": ops.normalize_code(block_content)
                        })
            except (SyntaxError, TypeError):
                continue
        return all_blocks

    async def analyze_state(self, state: State) -> Proposal:
        """
        Analyzes the code from the previous state for duplication and proposes
        orthogonal refactorings.
        """
        schrodinger_dev_output = state.metadata.get("schrodinger_dev_output", {})
        files_to_check = schrodinger_dev_output.get("files_to_create", {})

        if not files_to_check or len(files_to_check) < 2:
            return Proposal(agent_name=self.name, task_type="refactor", payload={"refactoring_plans": [], "duplicates_found": []}, status=Status.SUCCESS)

        # 1. Extract all code blocks
        all_blocks = self._extract_code_blocks(files_to_check)
        if len(all_blocks) < 2:
            return Proposal(agent_name=self.name, task_type="refactor", payload={"refactoring_plans": [], "duplicates_found": []}, status=Status.SUCCESS)

        # 2. Cluster blocks by similarity using a graph-based approach
        similarity_threshold = self.config.get("similarity_threshold", 0.8)
        graph = nx.Graph()

        # Add a unique identifier to each block for graph node representation
        for i, block in enumerate(all_blocks):
            block['id'] = i
            graph.add_node(i, block=block)

        for i in range(len(all_blocks)):
            for j in range(i + 1, len(all_blocks)):
                block1 = all_blocks[i]
                block2 = all_blocks[j]

                # Don't compare blocks from the same file
                if block1["file_path"] == block2["file_path"]:
                    continue

                similarity = similarity_ops.ncd_similarity(block1["normalized"], block2["normalized"])

                if similarity >= similarity_threshold:
                    graph.add_edge(block1['id'], block2['id'], weight=similarity)

        # 3. Find clusters (connected components)
        clusters = [
            [graph.nodes[node_id]['block'] for node_id in component]
            for component in nx.connected_components(graph)
            if len(component) > 1
        ]

        if not clusters:
            return Proposal(
                agent_name=self.name,
                task_type="refactor",
                payload={"refactoring_plans": [], "duplicates_found": []},
                status=Status.SUCCESS,
                reason="No highly similar code blocks found."
            )

        # For now, we'll just report the found clusters.
        # The next step will be to generate refactoring plans for them.
        # This part will be completed in the next plan step.
        duplicates_found = []
        for cluster in clusters:
            # For simplicity, just recording the first pair of the cluster as a duplicate
            if len(cluster) > 1:
                 duplicates_found.append({
                    "type": "similar_cluster",
                    "files": [item['file_path'] for item in cluster],
                    "blocks": [item['content'] for item in cluster]
                })

        # 4. Generate refactoring plans for each cluster
        plan_coros = [self._generate_refactoring_plan_for_cluster(cluster) for cluster in clusters]
        refactoring_plans_results = await asyncio.gather(*plan_coros, return_exceptions=True)

        valid_plans = [p for p in refactoring_plans_results if not isinstance(p, Exception)]

        # The `duplicates_found` format from the previous version is more detailed.
        # We can use it for calculating energy impact.
        return Proposal(
            agent_name=self.name,
            task_type="refactor",
            payload={"refactoring_plans": valid_plans, "duplicates_found": duplicates_found},
            status=Status.SUCCESS
        )

    async def _generate_refactoring_plan_for_cluster(self, cluster: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Helper to generate a refactoring plan for a cluster of similar blocks."""
        prompt_spec = prompts.get_prompt("generate_refactoring_plan", version="2.0")

        # Format the code blocks for the prompt
        code_blocks_section = ""
        for i, block in enumerate(cluster):
            code_blocks_section += f"Code Block {i+1} (from `{block['file_path']}`):\n"
            code_blocks_section += f"```python\n{block['content']}\n```\n\n"

        formatted_prompt = prompt_spec.format(code_blocks_section=code_blocks_section.strip())

        llm_response = await self.llm_client.complete({"prompt": formatted_prompt})
        plan = ops.parse_cluster_refactoring_plan(llm_response["content"])
        return plan

    def validate_proposal(self, proposal: Proposal) -> bool:
        """
        Validates the refactoring plans in the proposal.
        """
        if proposal.status != Status.SUCCESS:
            return False

        for plan in proposal.payload.get("refactoring_plans", []):
            if not all(k in plan for k in ["shared_component_path", "refactored_code", "replacement_plan"]):
                return False
            if not isinstance(plan.get("replacement_plan"), list):
                return False
        return True

    def execute(self, proposal: Proposal) -> Action:
        """
        Executes the proposal by calculating the energy impact of the refactoring.
        """
        refactoring_plans = proposal.payload.get("refactoring_plans", [])
        duplicates = proposal.payload.get("duplicates_found", [])

        # 1. Calculate the reduction in interaction energy
        # A simple model: energy reduction is proportional to the number and size of duplicates found.
        # This represents a reduction in coupling.
        coupling_reduction = 0
        for cluster in duplicates:
            # Add the lengths of all duplicated blocks in the cluster
            for block_content in cluster.get("blocks", []):
                coupling_reduction += len(block_content)

        # This metric can be used by the energy calculator
        interaction_metrics = {
            "coupling_reduction": float(coupling_reduction)
        }

        # We assume the calculator can handle a negative contribution
        # or has a specific method for calculating energy changes.
        # For now, let's calculate a simple negative energy impact.
        # Let's say each character of duplicated code removed reduces energy.
        energy_reduction = self.energy_calculator.config.get("w_coupling_reduction", 0.1) * coupling_reduction

        # 2. Create the action
        action_data = {
            "refactoring_plans": refactoring_plans,
            "energy_impact": {
                # This is an energy *reduction*
                "interaction": -energy_reduction
            }
        }

        return Action(
            task_id=proposal.id,
            agent_name=self.name,
            action_taken=True,
            status=Status.SUCCESS,
            result=action_data,
        )
