# agents/pauli_guard/ops.py
"""
Operations for the PauliGuard Agent.

This module contains the logic for detecting duplicated and similar code,
a core function for maintaining system orthogonality. It also provides
utilities for parsing the refactoring plans generated by the LLM.
"""

import json
import hashlib
import re
import ast
from typing import Dict, List, Tuple, Any


class RefactoringPlanError(Exception):
    """Custom exception for errors in refactoring plans."""
    pass

def levenshtein_distance(s1: str, s2: str) -> int:
    """
    Computes the Levenshtein (edit) distance between two sequences.
    This is useful for comparing code structures represented as strings.
    """
    if len(s1) < len(s2):
        return levenshtein_distance(s2, s1)

    if len(s2) == 0:
        return len(s1)

    previous_row = range(len(s2) + 1)
    for i, c1 in enumerate(s1):
        current_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previous_row[j + 1] + 1
            deletions = current_row[j] + 1
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row

    return previous_row[-1]

class _IdentifierVisitor(ast.NodeTransformer):
    def visit_Name(self, node: ast.Name) -> ast.Name:
        if node.id in __builtins__:
            return node
        return ast.Name(id='_var_', ctx=node.ctx)

    def visit_arg(self, node: ast.arg) -> ast.arg:
        return ast.arg(arg='_arg_', annotation=node.annotation)

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.FunctionDef:
        node.name = '_func_'
        self.generic_visit(node)
        return node

def normalize_code(code: str) -> str:
    """
    Normalizes a code string for comparison by parsing it to an AST,
    replacing identifiers, and then unparsing it back to a string.
    """
    try:
        tree = ast.parse(code)
        tree = _IdentifierVisitor().visit(tree)
        return ast.unparse(tree)
    except (SyntaxError, TypeError):
        code = re.sub(r'#.*', '', code)
        code = re.sub(r'\"\"\"(.*?)\"\"\"', '', code, flags=re.DOTALL)
        code = re.sub(r"'''(.*?)'''", '', code, flags=re.DOTALL)
        code = "".join(code.split())
        return code.lower()


def detect_duplicates(
    file_map: Dict[str, str],
    min_lines: int = 5,
    similarity_threshold: float = 0.95
) -> List[Dict[str, Any]]:
    """
    Detects duplicated and highly similar code blocks across a set of files.
    """
    all_blocks = []
    for file_path, content in file_map.items():
        try:
            tree = ast.parse(content)
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
                    block_content = ast.unparse(node)
                    if len(block_content.splitlines()) < min_lines:
                        continue

                    normalized_block = normalize_code(block_content)

                    all_blocks.append({
                        "file_path": file_path,
                        "start_line": node.lineno,
                        "content": block_content,
                        "normalized": normalized_block,
                        "hash": hashlib.sha256(normalized_block.encode()).hexdigest()
                    })
        except (SyntaxError, TypeError):
            continue # Skip files that are not valid python

    duplicates = []
    found_hashes = set()

    for i in range(len(all_blocks)):
        for j in range(i + 1, len(all_blocks)):
            block1 = all_blocks[i]
            block2 = all_blocks[j]

            if block1["file_path"] == block2["file_path"]:
                continue

            if block1["hash"] == block2["hash"]:
                if block1["hash"] not in found_hashes:
                    duplicates.append({
                        "type": "exact",
                        "block_1": {"file_path": block1["file_path"], "content": block1["content"]},
                        "block_2": {"file_path": block2["file_path"], "content": block2["content"]},
                        "similarity": 1.0
                    })
                    found_hashes.add(block1["hash"])
            else:
                distance = levenshtein_distance(block1["normalized"], block2["normalized"])
                max_len = max(len(block1["normalized"]), len(block2["normalized"]))
                similarity = 1 - (distance / max_len) if max_len > 0 else 1.0

                if similarity >= similarity_threshold:
                    duplicates.append({
                        "type": "similar",
                        "block_1": {"file_path": block1["file_path"], "content": block1["content"]},
                        "block_2": {"file_path": block2["file_path"], "content": block2["content"]},
                        "similarity": similarity
                    })

    return duplicates


def parse_refactoring_plan(llm_output: str) -> Dict[str, Any]:
    """
    Parses the JSON output from the LLM into a refactoring plan dictionary.
    """
    try:
        plan = json.loads(llm_output)
        required_keys = ["shared_component_path", "refactored_code", "replacement_plan"]
        if not all(key in plan for key in required_keys):
            raise RefactoringPlanError("LLM output is missing required keys for the refactoring plan.")

        if not isinstance(plan["replacement_plan"], list) or len(plan["replacement_plan"]) != 2:
            raise RefactoringPlanError("Replacement plan must be a list of two items.")

        return plan
    except json.JSONDecodeError:
        raise RefactoringPlanError("Failed to decode LLM output as JSON.")

def parse_cluster_refactoring_plan(llm_output: str) -> Dict[str, Any]:
    """
    Parses the JSON output from the LLM for a cluster refactoring plan.
    """
    try:
        plan = json.loads(llm_output)
        required_keys = ["shared_component_path", "refactored_code", "replacement_plan"]
        if not all(key in plan for key in required_keys):
            raise RefactoringPlanError("LLM output is missing required keys for the refactoring plan.")

        if not isinstance(plan["replacement_plan"], list) or len(plan["replacement_plan"]) < 2:
            raise RefactoringPlanError("Replacement plan must be a list of at least two items.")

        return plan
    except json.JSONDecodeError:
        raise RefactoringPlanError("Failed to decode LLM output as JSON.")
