"""
A comprehensive security framework with cryptographic verification, supply chain
integrity, capability-based security, immutable audit trails, and mathematical
security proofs.
"""

import hashlib
import json
from datetime import datetime, timezone
from typing import List, Optional, Any, Dict, Set

import z3
import nacl.signing
import nacl.encoding
from nacl.exceptions import BadSignatureError
from pydantic import BaseModel, Field

# --- Data Structures for Inputs and Outputs ---

class SBOMDependency(BaseModel):
    """Represents a single dependency in an SBOM."""
    name: str
    version: str
    license: str

class Artifact(BaseModel):
    """Represents a software artifact to be verified."""
    name: str
    content: bytes
    digest: str  # SHA-256 hash of the content
    sbom: Optional[List[SBOMDependency]] = None

class SBOMRequirement(BaseModel):
    """Specifies requirements for an artifact's Software Bill of Materials."""
    allowed_licenses: List[str]
    blocked_packages: List[str]

class CapabilityToken(BaseModel):
    """A capability token granting specific permissions, signed with Ed25519."""
    granted_capabilities: List[str]
    expiry: datetime
    public_key: str  # Hex-encoded public key
    signature: Optional[str] = None  # Hex-encoded signature

    def to_signed_message(self) -> bytes:
        """Creates the canonical message representation for signing/verification."""
        return self.model_dump_json(exclude={'signature'}).encode('utf-8')

class SystemOperation(BaseModel):
    """Represents a system operation to be secured and verified."""
    operation_name: str
    required_capabilities: List[str]
    capability_tokens: List[str]  # Serialized and hex-encoded CapabilityTokens
    mathematical_security_constraints: List[str]  # Z3 constraints as SMT-LIB2 strings
    artifacts: List[Artifact]
    sbom_requirements: SBOMRequirement
    artifact_signatures: Dict[str, str]  # artifact.name -> hex-encoded signature

class CapabilityVerification(BaseModel):
    """Result of the capability verification process."""
    verified: bool
    reason: str = ""
    granted_capabilities: Optional[Set[str]] = None

class SupplyChainVerification(BaseModel):
    """Result of the supply chain integrity verification."""
    verified: bool
    reason: str = ""

class CryptographicProof(BaseModel):
    """A formal cryptographic proof generated by the system."""
    proof_id: str
    proof_data: str  # A Z3 expression string
    description: str

class MathematicalSecurityVerification(BaseModel):
    """Result of the mathematical verification of security properties."""
    verified: bool
    reason: str = ""

class AuditRecord(BaseModel):
    """An immutable record of a security verification operation."""
    record_id: str
    timestamp: datetime
    operation: SystemOperation
    security_verifications: List[Any]
    cryptographic_proofs: List[CryptographicProof]
    mathematical_security_certificate: str

    @property
    def immutable_id(self) -> str:
        """Computes a secure hash of the record to serve as an immutable ID."""
        record_str = self.model_dump_json(exclude={'record_id'})
        return hashlib.sha256(record_str.encode()).hexdigest()

class SecurityVerificationResult(BaseModel):
    """The final, comprehensive result of the security verification process."""
    operation_security_approved: bool
    capability_verification: CapabilityVerification
    supply_chain_verification: SupplyChainVerification
    cryptographic_proofs: List[CryptographicProof]
    mathematical_security_verification: MathematicalSecurityVerification
    immutable_audit_record_id: str
    comprehensive_security_certificate: str

# --- Engine Implementations ---

class CapabilityBasedSecurityEngine:
    """Verifies capability tokens and mathematical constraints."""
    async def verify_comprehensive_capabilities(
        self,
        operation_capabilities: List[str],
        provided_tokens: List[str],
        mathematical_constraints: List[str]
    ) -> CapabilityVerification:
        all_granted_capabilities = set()
        if not provided_tokens:
            return CapabilityVerification(verified=False, reason="No capability tokens provided.")

        for token_str in provided_tokens:
            try:
                token = CapabilityToken.model_validate(json.loads(token_str))
                if not token.signature:
                    return CapabilityVerification(verified=False, reason="Token is missing a signature.")

                verify_key = nacl.signing.VerifyKey(token.public_key, encoder=nacl.encoding.HexEncoder)
                verify_key.verify(token.to_signed_message(), nacl.encoding.HexEncoder.decode(token.signature))

                if token.expiry.replace(tzinfo=timezone.utc) < datetime.now(timezone.utc):
                    return CapabilityVerification(verified=False, reason="Capability token has expired.")

                all_granted_capabilities.update(token.granted_capabilities)
            except BadSignatureError:
                return CapabilityVerification(verified=False, reason="Invalid signature on capability token.")
            except (json.JSONDecodeError, ValueError) as e:
                return CapabilityVerification(verified=False, reason=f"Failed to parse capability token: {e}")

        if not set(operation_capabilities).issubset(all_granted_capabilities):
            missing = set(operation_capabilities) - all_granted_capabilities
            return CapabilityVerification(verified=False, reason=f"Missing capabilities: {', '.join(missing)}")

        # Verify mathematical constraints using Z3
        solver = z3.Solver()
        all_caps = all_granted_capabilities | set(operation_capabilities)

        # Build a single SMT-LIB string with all declarations and assertions
        smt_lib_parts = []
        # 1. Declare all capabilities as boolean constants
        for cap in all_caps:
            smt_lib_parts.append(f"(declare-const {cap} Bool)")
        # 2. Assert the capabilities that have been granted
        for cap in all_granted_capabilities:
            smt_lib_parts.append(f"(assert {cap})")
        # 3. Add the user-provided mathematical constraints
        for constraint in mathematical_constraints:
            smt_lib_parts.append(f"(assert {constraint})")

        full_smt_lib_script = "\n".join(smt_lib_parts)

        try:
            solver.from_string(full_smt_lib_script)
        except z3.Z3Exception as e:
             return CapabilityVerification(verified=False, reason=f"Failed to parse mathematical constraint: {e}")

        if solver.check() == z3.unsat:
            return CapabilityVerification(verified=False, reason="Mathematical security constraints are unsatisfiable.")

        return CapabilityVerification(verified=True, reason="All capabilities verified.", granted_capabilities=all_granted_capabilities)

class SupplyChainIntegrityVerifier:
    """Verifies the integrity of software artifacts and their supply chain."""
    async def verify_complete_supply_chain_integrity(
        self,
        artifacts: List[Artifact],
        sbom_requirements: SBOMRequirement,
        cryptographic_signatures: Dict[str, str],
        capability_tokens: List[str]
    ) -> SupplyChainVerification:
        # First, get a set of trusted public keys from valid capability tokens
        trusted_keys = set()
        for token_str in capability_tokens:
            try:
                token = CapabilityToken.model_validate(json.loads(token_str))
                if not token.signature: continue
                verify_key = nacl.signing.VerifyKey(token.public_key, encoder=nacl.encoding.HexEncoder)
                verify_key.verify(token.to_signed_message(), nacl.encoding.HexEncoder.decode(token.signature))
                if token.expiry.replace(tzinfo=timezone.utc) >= datetime.now(timezone.utc):
                    trusted_keys.add(verify_key)
            except (BadSignatureError, json.JSONDecodeError, ValueError):
                continue

        if not trusted_keys:
            return SupplyChainVerification(verified=False, reason="No valid public keys found in capability tokens to verify artifact signatures.")

        for artifact in artifacts:
            # Verify artifact content digest
            if hashlib.sha256(artifact.content).hexdigest() != artifact.digest:
                return SupplyChainVerification(verified=False, reason=f"Digest mismatch for artifact: {artifact.name}")

            # Verify artifact signature
            signature_hex = cryptographic_signatures.get(artifact.name)
            if not signature_hex:
                return SupplyChainVerification(verified=False, reason=f"Missing signature for artifact: {artifact.name}")

            signature_bytes = nacl.encoding.HexEncoder.decode(signature_hex)
            is_signature_valid = any(
                self._verify_signature(key, artifact.content, signature_bytes) for key in trusted_keys
            )
            if not is_signature_valid:
                return SupplyChainVerification(verified=False, reason=f"Invalid signature for artifact: {artifact.name}")

            # Verify SBOM
            if artifact.sbom:
                for dep in artifact.sbom:
                    if dep.name in sbom_requirements.blocked_packages:
                        return SupplyChainVerification(verified=False, reason=f"Artifact '{artifact.name}' has a blocked dependency: {dep.name}")
                    if dep.license not in sbom_requirements.allowed_licenses:
                        return SupplyChainVerification(verified=False, reason=f"Artifact '{artifact.name}' has a dependency with an unallowed license: {dep.license}")

        return SupplyChainVerification(verified=True, reason="Supply chain integrity verified.")

    def _verify_signature(self, key: nacl.signing.VerifyKey, message: bytes, signature: bytes) -> bool:
        try:
            key.verify(message, signature)
            return True
        except BadSignatureError:
            return False

class CryptographicProofEngine:
    """Generates comprehensive cryptographic proofs of security."""
    async def generate_comprehensive_security_proofs(
        self,
        operation: SystemOperation,
        capability_verification: CapabilityVerification,
        supply_chain_verification: SupplyChainVerification
    ) -> List[CryptographicProof]:
        if not capability_verification.verified or not supply_chain_verification.verified:
            return []

        proof_parts = []
        # Declare all capabilities and artifacts as boolean constants in Z3
        all_caps = capability_verification.granted_capabilities | set(operation.required_capabilities)
        proof_parts.extend([f"(declare-const {cap} Bool)" for cap in all_caps])
        proof_parts.extend([f"(declare-const artifact_{artifact.name}_valid Bool)" for artifact in operation.artifacts])

        # Assert the verified properties as true
        proof_parts.extend([f"(assert {cap})" for cap in capability_verification.granted_capabilities])
        proof_parts.extend([f"(assert artifact_{artifact.name}_valid)" for artifact in operation.artifacts])

        # Add the operation's mathematical constraints
        proof_parts.extend([f"(assert {c})" for c in operation.mathematical_security_constraints])

        proof_data = "\n".join(proof_parts)
        return [CryptographicProof(
            proof_id=f"proof_{operation.operation_name}_{datetime.now(timezone.utc).isoformat()}",
            proof_data=proof_data,
            description="Comprehensive proof of security properties for the operation."
        )]

class ImmutableAuditTrailSystem:
    """Creates immutable, verifiable audit records."""
    async def create_comprehensive_audit_record(
        self,
        operation: SystemOperation,
        security_verifications: List[Any],
        cryptographic_proofs: List[CryptographicProof],
        mathematical_security_certificate: str
    ) -> AuditRecord:
        record = AuditRecord(
            record_id="",  # Will be replaced by the immutable hash
            timestamp=datetime.now(timezone.utc),
            operation=operation,
            security_verifications=security_verifications,
            cryptographic_proofs=cryptographic_proofs,
            mathematical_security_certificate=mathematical_security_certificate,
        )
        record.record_id = record.immutable_id
        return record

class MathematicalSecurityVerifier:
    """Verifies the mathematical consistency of security proofs."""
    async def verify_mathematical_security_properties(
        self,
        operation: SystemOperation,
        security_proofs: List[CryptographicProof],
        audit_record: AuditRecord
    ) -> MathematicalSecurityVerification:
        if not security_proofs:
            # If there are no proofs (e.g., due to prior failure), this step is vacuously true.
            return MathematicalSecurityVerification(verified=True, reason="No security proofs to verify.")

        solver = z3.Solver()
        try:
            full_proof = "\n".join([p.proof_data for p in security_proofs])
            solver.from_string(full_proof)
            result = solver.check()

            if result == z3.sat:
                return MathematicalSecurityVerification(verified=True, reason="Mathematical security properties are consistent and hold.")
            elif result == z3.unsat:
                # This indicates a contradiction in the proofs, which is a critical failure.
                return MathematicalSecurityVerification(verified=False, reason="Contradiction found in security proofs.")
            else:
                return MathematicalSecurityVerification(verified=False, reason=f"Could not determine satisfiability of security proofs: {result}")
        except z3.Z3Exception as e:
            return MathematicalSecurityVerification(verified=False, reason=f"Failed to parse or solve security proofs: {e}")

class QuantumCryptographicSecurityFramework:
    """Complete security framework with cryptographic verification and mathematical proofs"""

    def __init__(self):
        self.capability_security_engine = CapabilityBasedSecurityEngine()
        self.supply_chain_verifier = SupplyChainIntegrityVerifier()
        self.cryptographic_prover = CryptographicProofEngine()
        self.immutable_audit_system = ImmutableAuditTrailSystem()
        self.mathematical_security_verifier = MathematicalSecurityVerifier()

    async def secure_complete_system_operation(self, operation: SystemOperation) -> SecurityVerificationResult:
        """Apply complete security verification with mathematical guarantees"""

        # 1. Verify cryptographic capability tokens with Ed25519 signatures
        capability_verification = await self.capability_security_engine.verify_comprehensive_capabilities(
            operation_capabilities=operation.required_capabilities,
            provided_tokens=operation.capability_tokens,
            mathematical_constraints=operation.mathematical_security_constraints
        )

        # 2. Verify supply chain integrity with cryptographic attestations
        supply_chain_verification = await self.supply_chain_verifier.verify_complete_supply_chain_integrity(
            artifacts=operation.artifacts,
            sbom_requirements=operation.sbom_requirements,
            cryptographic_signatures=operation.artifact_signatures,
            capability_tokens=operation.capability_tokens # Pass tokens for key extraction
        )

        # 3. Generate comprehensive cryptographic security proofs
        security_proofs = await self.cryptographic_prover.generate_comprehensive_security_proofs(
            operation=operation,
            capability_verification=capability_verification,
            supply_chain_verification=supply_chain_verification
        )

        # 4. Create immutable audit record with mathematical verification
        math_cert = self._generate_mathematical_security_certificate(security_proofs)
        audit_record = await self.immutable_audit_system.create_comprehensive_audit_record(
            operation=operation,
            security_verifications=[capability_verification, supply_chain_verification],
            cryptographic_proofs=security_proofs,
            mathematical_security_certificate=math_cert
        )

        # 5. Verify mathematical security properties
        mathematical_security_verification = await self.mathematical_security_verifier.verify_mathematical_security_properties(
            operation=operation,
            security_proofs=security_proofs,
            audit_record=audit_record
        )

        # 6. Aggregate results and generate final certificate
        is_approved = all([
            capability_verification.verified,
            supply_chain_verification.verified,
            mathematical_security_verification.verified
        ])

        comprehensive_cert = self._generate_comprehensive_security_certificate(
            capability_verification, supply_chain_verification, security_proofs, mathematical_security_verification
        )

        return SecurityVerificationResult(
            operation_security_approved=is_approved,
            capability_verification=capability_verification,
            supply_chain_verification=supply_chain_verification,
            cryptographic_proofs=security_proofs,
            mathematical_security_verification=mathematical_security_verification,
            immutable_audit_record_id=audit_record.immutable_id,
            comprehensive_security_certificate=comprehensive_cert
        )

    def _generate_mathematical_security_certificate(self, security_proofs: List[CryptographicProof]) -> str:
        """Generates a mathematical security certificate."""
        if security_proofs:
            proof_hash = hashlib.sha256("\n".join(p.proof_data for p in security_proofs).encode()).hexdigest()
            return f"MathematicalSecurityCertificate:Valid:{proof_hash}"
        return "MathematicalSecurityCertificate:NoProofsGenerated"

    def _generate_comprehensive_security_certificate(
        self,
        capability_verification: CapabilityVerification,
        supply_chain_verification: SupplyChainVerification,
        security_proofs: List[CryptographicProof],
        mathematical_security_verification: MathematicalSecurityVerification
    ) -> str:
        """Generates a final, comprehensive security certificate."""
        status = "APPROVED" if all([
            capability_verification.verified,
            supply_chain_verification.verified,
            mathematical_security_verification.verified
        ]) else "REJECTED"

        certificate_data = {
            "status": status,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "capability_verified": capability_verification.verified,
            "supply_chain_verified": supply_chain_verification.verified,
            "math_verified": mathematical_security_verification.verified,
        }
        cert_hash = hashlib.sha256(json.dumps(certificate_data, sort_keys=True).encode()).hexdigest()
        return f"ComprehensiveSecurityCertificate:{status}:{cert_hash}"
